routes/web.php
<?php

Route::resource('project' , 'ProjectController');
Route::get('project/{project}/copy','ProjectController@copy')->name('project.copy');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class project extends Model
{
    protected $fillable = ['name'];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\project;

class ProjectController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    
    public function index()
    {
        $project = project::all();
        return view('project.index' , compact('project'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('project.create');

    }



    public function store(Request $request, project $project)
    {
        $data =$request->validate(['name' => 'required']);

        $project = tap(new project($data))->save();
        return redirect()->route('project.index');
      }



    public function show(project $project)
    {
        return view('project.show' , compact('project'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(project $project)
    {
        return view('project.edit' , compact('project'));
    }


    public function copy(project $project)
    {
        return view('project.copy' , compact('project'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, project $project)
    {
      $data =$request->validate(['name' => 'required']);

      $project->name = $data['name'];
      $project->save();
      return redirect()->route('project.index');
    }


    public function destroy(project $project)
    {
        $project->delete();
        return redirect()->route('project.index');
    }
}

resources/views/project/copy.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{{__('pages/projectIndex.title')}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1"> <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  </head>
  <body>
<form class="form" action="{{route('project.store',['id'=>$project->id])}}" method="post">
  {{ csrf_field() }}
<input type="text" name="name" value="{{$project->name}}">
<button>save</button>
</form>
  </body>
</html>

resources/views/project/create.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{{__('pages/projectIndex.title')}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1"> <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  </head>
  <body>
<form class="form" action="{{route('project.store')}}" method="post">
  {{ csrf_field() }}
<input type="text" name="name" placeholder="company name">
<button type="submit" name="button">save</button>
</form>
  </body>
</html>

resources/views/project/edit.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{{__('pages/projectIndex.title')}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1"> <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  </head>
  <body>
<form class="form" action="{{route('project.update',['id'=>$project->id])}}" method="post">
  {{ csrf_field() }}
<input type="hidden" name="_method" value="PUT">
<input type="text" name="name" value="{{$project->name}}">
<button>update</button>
</form>
  </body>
</html>

resources/views/project/index.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{{__('pages/projectIndex.title')}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1"> <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  </head>
  <body>
<h1>Projects</h1>
<a href="{{route('project.create')}}"><h3>create new</h3> </a>
@foreach($project as $project)
<hr>
<a href="{{route('project.show', ['id' => $project->id ])}}"><h3>{{$project->name}}</h3></a>
<form  action="{{route('project.destroy',['id' => $project->id ])}}" method="post">
  {{ csrf_field() }}
  {{ method_field('DELETE') }}
  <button >delete</button>
</form>
<a href="{{route('project.edit',['id' => $project->id])}}">Edit</a>
@endforeach

</body>
</html>

resources/views/project/show.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <a href="{{route('project.index')}}">go back home</a>
    <table>
      <tr>
        <th>id</th>
        <th>name</th>
      </tr>
      <tr>
        <td>{{$project->id}}</td>
        <td>{{$project->name}}</td>
        <td><form  action="{{route('project.destroy',['id' => $project->id ])}}" method="post">
          {{ csrf_field() }}
          {{ method_field('DELETE') }}
          <button >delete</button>
        </form></td>
        <td><a href="{{route('project.edit',['id' => $project->id])}}">Edit</a></td>
        <td><a href="{{route('project.copy',['id' => $project->id])}}">copy</a></td>
      </tr>
    </table>
  </body>
</html>